backend:
  name: git-gateway
  #name: github
  #repo: drap54/ds-gitlab
  #branch: master

publish_mode: editorial_workflow  
media_folder: static/marketing/img
public_folder: /marketing/img

collections:
  - name: 'VJLP1-NoForm'
    label: 'Vera&John Template 1'
    format: 'frontmatter'
    folder: 'assets/content/landing-page/marketing/vjlp1'
    create: true
    identifier_field: "promo_banner.promo_title"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: vjlp1/{{slug}}
    show_preview_links: false
    editor:
      preview: false
    fields:
      - label: "Locale"
        name: "promo_locale"
        widget: "object"
        colapsed: true
        fields:
          - label: "Country Code"
            name: "promo_country_code"
            widget: "select"
            default: ["jp"]  
            options:
              - { label: "Japan", value: "jp" }
              - { label: "Sweden", value: "se" }
              - { label: "Germany", value: "de" }
          - label: "Language Code"
            name: "promo_language_code"
            widget: "select"
            default: ["ja"]   
            options:
              - { label: "Japanese", value: "ja" }
              - { label: "Swedish", value: "sv" }
              - { label: "German", value: "de" } 
      - label: "Promotion Banner"
        name: "promo_banner" 
        widget: "object"
        collapsed: true
        fields:
          - {label: "Title", name: "promo_title", widget: "string"}
          - {label: "Display Title", name: "promo_title_display", widget: "boolean", default: true}
          - {label: "Subtitle", name: "promo_subtitle", widget: "string", required: false}
          - {label: "Login Button", name: promo_login_button, widget: "string"}
          - {label: "Login Button Redirect URL", name: promo_login_button_redirect_url, widget: "string"}    
          - {label: "Join Button", name: promo_join_button, widget: "string"}
          - {label: "Join Button Redirect URL", name: promo_join_button_redirect_url, widget: "string"}
          - label: "Images"
            name: "promo_images"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Desktop Background", name: promo_bg_desktop, widget: image}
              - {label: "Mobile Background", name: promo_bg_mobile, widget: image}
              - {label: "Game Logo", name: promo_game_logo, widget: image, required: false}
      - label: "Promotion Steps"
        name: "promo_steps" 
        widget: "object"
        collapsed: true
        fields:
          - {label: "Step 1 Title", name: promo_step_1_title, widget: "string"}
          - {label: "Step 1 Description", name: promo_step_1_desc, widget: "string"}
          - {label: "Step 2 Title", name: promo_step_2_title, widget: "string"}
          - {label: "Step 2 Description", name: promo_step_2_desc, widget: "string"}
          - {label: "Step 3 Title", name: promo_step_3_title, widget: "string"}
          - {label: "Step 3 Description", name: promo_step_3_desc, widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}    
      - {label: Template, name: promo_template, widget: hidden, default: "VJLP1-NoForm"}

  - name: "VJLP3-NoForm"
    label: "Vera&John Template 3"
    format: 'frontmatter'
    folder: "assets/content/landing-page/marketing/vjlp3"
    create: true
    identifier_field: "promo_banner.promo_title"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: vjlp3/{{slug}}
    show_preview_links: false
    editor:
      preview: false
    fields:
      - label: "Locale"
        name: "promo_locale"
        widget: "object"
        colapsed: true
        fields:
          - label: "Country Code"
            name: "promo_country_code"
            widget: "select"
            default: ["jp"]  
            options:
              - { label: "Japan", value: "jp" }
              - { label: "Sweden", value: "se" }
              - { label: "Germany", value: "de" }
          - label: "Language Code"
            name: "promo_language_code"
            widget: "select"
            default: ["ja"]   
            options:
              - { label: "Japanese", value: "ja" }
              - { label: "Swedish", value: "sv" }
              - { label: "German", value: "de" } 
      - label: "Promotion Banner"
        name: "promo_banner" 
        widget: "object"
        collapsed: true
        fields:
          - {label: "Title", name: "promo_title", widget: "string"}
          - {label: "Display Title", name: "promo_title_display", widget: "boolean", default: true}
          - {label: "Subtitle", name: "promo_subtitle", widget: "string", required: false}
          - {label: "Login Button", name: promo_login_button, widget: "string"}   
          - {label: "Login Button Redirect URL", name: promo_login_button_redirect_url, widget: "string"}     
          - {label: "Join Button", name: promo_join_button, widget: "string"}
          - label: "Join Button Location"
            name: "promo_join_button_location"
            widget: "select"
            default: ["hidden"]
            options:
              - { label: "Upper Left", value: "upper-left" }
              - { label: "Lower Right", value: "lower-right" }
              - { label: "Hidden", value: "hidden" }
          - {label: "Join Button Redirect URL", name: promo_join_button_redirect_url, widget: "string"}    
          - label: "Images"
            name: "promo_images"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Desktop Background", name: promo_bg_desktop, widget: image}
              - {label: "Mobile Background", name: promo_bg_mobile, widget: image}
          - label: "Game Slider"
            name: "game_images"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Game Icon 1", name: game_icon_1, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_1, widget: string, required: false, default: ""}
              - {label: "Game Icon 2", name: game_icon_2, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_2, widget: string, required: false, default: ""}
              - {label: "Game Icon 3", name: game_icon_3, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_3, widget: string, required: false, default: ""}
              - {label: "Game Icon 4", name: game_icon_4, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_4, widget: string, required: false, default: ""}
              - {label: "Game Icon 5", name: game_icon_5, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_5, widget: string, required: false, default: ""}
              - {label: "Game Icon 6", name: game_icon_6, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_6, widget: string, required: false, default: ""}
      - {label: Template, name: promo_template, widget: hidden, default: "VJLP3-NoForm"}
      - {label: 'Body', name: 'body', widget: 'markdown' }

  - name: "VJ-Homapage"
    label: "Vera&John Homepage"
    format: 'frontmatter'
    folder: "assets/content/landing-page/marketing/vjlp3"
    create: true
    identifier_field: "home_title"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: vjhp/{{slug}}
    show_preview_links: false
    editor:
      preview: false
    fields:
      - label: "Section 1"
        name: "section_1_home_header" 
        widget: "object"
        collapsed: true
        fields:
          - {label: "Header Login Text", name: header_login_text, widget: "string"}
          - {label: "Span Login Anchor", name: span_login_anchor, widget: "string"}
          - {label: "Span Login Anchor Redirect URL", name: span_login_anchor_redirect_url, widget: "string"}
          - {label: "Home Title", name: "home_title", widget: "string"}
          - {label: "Home Subtitle", name: "home_subtitle", widget: "string", required: false}
          - {label: "Header Display Text", name: "header_display_text", widget: "string", required: false}
          - label: "Homepage Game Slider"
            name: "homepage_game_slider"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Home Game Icon 1", name: home_game_icon_1, widget: image, required: false, default: ""}
              - {label: "Home Game URL", name: home_game_url_1, widget: string, required: false, default: ""}
              - {label: "Home Game Icon 2", name: home_game_icon_2, widget: image, required: false, default: ""}
              - {label: "Home Game URL", name: home_game_url_2, widget: string, required: false, default: ""}
              - {label: "Home Game Icon 3", name: home_game_icon_3, widget: image, required: false, default: ""}
              - {label: "Home Game URL", name: home_game_url_3, widget: string, required: false, default: ""}
              - {label: "Home Game Icon 4", name: home_game_icon_4, widget: image, required: false, default: ""}
              - {label: "Home Game URL", name: home_game_url_4, widget: string, required: false, default: ""}
              - {label: "Home Game Icon 5", name: home_game_icon_5, widget: image, required: false, default: ""}
              - {label: "Home Game URL", name: home_game_url_5, widget: string, required: false, default: ""}
              - {label: "Home Game Icon 6", name: home_game_icon_6, widget: image, required: false, default: ""}
              - {label: "Home Game URL", name: home_game_url_6, widget: string, required: false, default: ""}
          - {label: "Header Heading4", name: header_heading4, widget: "string"}
          - {label: "Header Text1", name: header_text1, widget: "string"}
          - {label: "Register Button", name: promo_register_button, widget: "string"}
          - {label: "Register Button Redirect URL", name: promo_register_button_redirect_url, widget: "string"} 
          - {label: "Header Text2", name: header_text2, widget: "string"}
      - label: "Section 3"
        name: "section_3_columns" 
        widget: "object"
        collapsed: true
        fields:
          - label: "Column 1"
            name: "section_3_column_1"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Heading", name: section_3_column_1_heading, widget: "string"}
              - {label: "Background Image", name: section_3_background_image_1, widget: image, required: false, default: ""}
              - {label: "Text", name: section_3_column_1_text, widget: "string"}
              - {label: "Button", name: section_3_column_1_button, widget: "string"}   
              - {label: "Button Redirect URL", name: section_3_column_1_button_redirect_url, widget: "string"} 
          - label: "Column 2"
            name: "section_3_column_2"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Heading", name: section_3_column_2_heading, widget: "string"}
              - {label: "Background Image", name: section_3_background_image_2, widget: image, required: false, default: ""}
              - {label: "Text", name: section_3_column_2_text, widget: "string"}
              - {label: "Button", name: section_3_column_2_button, widget: "string"}   
              - {label: "Button Redirect URL", name: section_3_column_2_button_redirect_url, widget: "string"}
      - label: "Section 6"
        name: "section_6"
        widget: "object"
        colapsed: true
        fields:
          - {label: "Heading", name: section_6_heading, widget: "string"}
          - {label: "Text 1", name: section_6_text_1, widget: "string"}
          - {label: "Text 2", name: section_6_text_2, widget: "string"}
          - {label: "Button Text", name: section_6_button_text, widget: "string"}   
          - {label: "Button Redirect URL", name: section_6_button_redirect_url, widget: "string"}
      - label: "Section 7"
        name: "section_7_columns" 
        widget: "object"
        collapsed: true
        fields:
          - label: "Column 1"
            name: "section_7_column_1"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Heading", name: section_7_column_1_heading, widget: "string"}
              - {label: "Text", name: section_7_column_1_text, widget: "string"}
              - {label: "Image", name: section_7_image_column_1, widget: image, required: false, default: ""}
          - label: "Column 2"
            name: "section_7_column_2"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Heading", name: section_7_column_2_heading, widget: "string"}
              - {label: "Text", name: section_7_column_2_text, widget: "string"}
              - {label: "Image", name: section_7_image_column_2, widget: image, required: false, default: ""}
      - label: "Section 8"
        name: "section_8"
        widget: "object"
        colapsed: true
        fields:
          - {label: "Heading", name: section_8_heading, widget: "string"}
          - {label: "Menu 1", name: section_8_menu_1_text, widget: "string"}   
          - {label: "Menu 1 Redirect URL", name: section_8_menu_1_redirect_url, widget: "string"}
          - {label: "Menu 2", name: section_8_menu_2_text, widget: "string"}   
          - {label: "Menu 2 Redirect URL", name: section_8_menu_2_redirect_url, widget: "string"}
          - {label: "Menu 3", name: section_8_menu_3_text, widget: "string"}   
          - {label: "Menu 3 Redirect URL", name: section_8_menu_3_redirect_url, widget: "string"}
          - {label: "Menu 4", name: section_8_menu_4_text, widget: "string"}   
          - {label: "Menu 4 Redirect URL", name: section_8_menu_4_redirect_url, widget: "string"}
      - {label: 'Footer', name: 'homepage_footer', widget: 'markdown' }